<a href="https://colab.research.google.com/github/Sidd-04/PythonLec/blob/master/03_04_2024_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MODULES IN PYTHON

Numpy is used to create nd arrays.
faster than tuples and list

In [ ]:
#Numpy is a general-purpose array-processing package.
import numpy as np
lst1=[1,2,3,4]
lst2=[5,6,7,8]
lst3=[20,11,0,1]
arr=np.array([lst1,lst2,lst3])
arr

#creating array from tuple

arr1=np.array((9,8,7,6))
arr1


arr1[1:] #start from  element located at index 1

arr1[:1]# start but end at location 1 but dont include index 1

arr[1:3, 1:2]

arr1[::2] #start,end, stepsize


a1=arr.reshape(4,3)
a1



a1[1:2,:2]
a1+=1


#Exploratory Data Analysis
arr
arr[arr<12]

##mechanism to create an array
np.arange(1,20,2).reshape(2,5)

##mechanism to create a 1D array
np.arange(1,20,2).reshape(2,5,1)


arr1*arr1

np.ones((5,4))

np.zeros((4,5))


np.random.randint(10,50,4).reshape(2,2)

np.random.randn(5,6)





In [19]:
import numpy as np

#List to array
lst1=[1,2,3,4]
l2=[5,6,7,8]
l3=[20,5,0,1]
Arr=np.array([lst1,l2,l3])
print(Arr)
Arr.reshape(4,3)

#tuple to array
t1=(5,6,0,3)
t2=(8,9,0,5)
Arr1=np.array([t1,t2])
print(Arr1)
k=Arr1[0:1,0:2]         #0:1 means 0th row and starting from 1st element  and 0:2 means starting from oth column to 2nd column.and note last wala excluded hai.
print(k)
k2=Arr1[1:,1:3]
print(k2)
np.arange(2,20).reshape(4,5)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [20  5  0  1]]
[[5 6 0 3]
 [8 9 0 5]]
[[5 6]]
[[9 0]]


In [23]:
np.arange(2,18).reshape(4,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
np.arange(2,18)

In [31]:
np.random.randint(0,50,4).reshape(2,2)

array([[10, 38],
       [31, 14]])