<a href="https://colab.research.google.com/github/Sidd-04/PythonLec/blob/master/Numpyfull.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.version)

# Creating a rank 1 Array
arr=np.array([1,2,3,4,5])
print("Array with Rank 1:\n", arr)
print(type(arr))

# Creating a rank 2 Array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

# Creating an array from tuple
arr=np.array((1,2,3,4,5))
print(arr)

arr1=arr[0:3]
print(arr1)



<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
Array with Rank 1:
 [1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]
[1 2 3]


In [ ]:
import numpy as np
import numpy as np
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)

# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]     #syntax for 2d array -> arr[row range,column range]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

# Printing elements at
# specific Indices
Index_arr = arr[[1,1,0,3],[3,2,1,0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [3]:
# Python Program to create
# a data type object
import numpy as np

# Integer datatype
# guessed by Numpy
x = np.array([1, 2])
print("Integer Datatype: ")
print(x.dtype)

# Float datatype
# guessed by Numpy
x = np.array([1.0, 2.0])
print("\nFloat Datatype: ")
print(x.dtype)

# Forced Datatype
x = np.array([1, 2], dtype = np.int64)
print("\nForcing a Datatype: ")
print(x.dtype)


Integer Datatype: 
int64

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [7]:
import numpy as np
arr1=np.array([[1,2,],[3,4]],dtype=np.float64)
arr2=np.array([[5,6],[7,8]],dtype=np.float64)
print(arr1)
print(arr2)
print(arr1+arr2)

# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
# Transpose of Array
# using In-built function 'T'
Trans_arr=arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
Addition of Two Arrays: 
[[ 6.  8.]
 [10. 12.]]

Addition of Array elements: 
10.0

Square root of Array1 elements: 
[[1.         1.41421356]
 [1.73205081 2.        ]]

Transpose of Array: 
[[1. 3.]
 [2. 4.]]


In [11]:
import numpy as geek
array1 = geek.arange(8)
print("Original array : \n", array1)

array2=geek.arange(8).reshape(2,4)
print("\narray reshaped with 2 rows and 4 columns : \n", array2)

# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
      array3)

#*** Constructs 3D array imp.
array4 = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
      array4)


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
# Python Program illustrating
# numpy.zeros method

import numpy as geek

b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
c = geek.zeros([3, 3])  #by default data type is float.
print("\nMatrix c : \n", c)
d=geek.zeros([2,2,3],dtype=str)
print("\nMatrix d : \n", d)


Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix d : 
 [[['' '' '']
  ['' '' '']]

 [['' '' '']
  ['' '' '']]]


In [14]:
import numpy as np

# create a float array of uninitialized entries
array1 = np.empty(5)

print('Float Array: ',array1)

# create an int array of arbitrary entries
array2 = np.empty(5, dtype = int)

print('Int Array: ',array2)


[                  0 4598175219545276416 4602678819172646912
 4604930618986332160 4607182418800017408]


In [20]:
import numpy as np

# create an array with first five elements
array1 = np.arange(5)

# create an array with elements from 5 to 10(exclusive)
array2 = np.arange(5, 10)

# create an array with elements from 5 to 15 with stepsize 2
array3 = np.arange(5, 15, 2)
print(array1)
print(array2)
print(array3)
# create an array with elements from 0 to 1 with stepsize 0.2
array4 = np.arange(0, 1, 0.2)

# elements between 10 and 40 with stepsize 4
array5 = np.arange(10, 50 ,4)

# generate 4 elements between 10 and 40
array6 = np.linspace(10, 50 ,4)  # includes 50   #imp
print(array4)
print(array5)
print(array6)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[0.  0.2 0.4 0.6 0.8]
[10 14 18 22 26 30 34 38 42 46]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [22]:
#mean of 1d array
import numpy as np

# create an array
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# calculate the mean of the array
avg = np.mean(array1)
print(avg)
# calculate the standard deviation of the array
deviation = np.std(array1)


print(deviation)

# Output: 2.29128784747792


3.5
2.29128784747792


In [28]:
#Mean of 2d array
import numpy as np

# create a 2D array
array1 = np.array([[1, 3],
                 [5, 7]])

# calculate the mean of the entire array
result1 = np.mean(array1)
print("Entire Array:",result1)  # 4.0

# calculate the mean along vertical axis (axis=0)
result2 = np.mean(array1, axis=0)
print("Along Vertical Axis:",result2)  # [3. 5.]

# calculate the mean along  (axis=1)
result3 = np.mean(array1, axis=1)
print("Along Horizontal Axis :",result3)  # [2. 6.]


Entire Array: 4.0
Along Vertical Axis: [3. 5.]
Along Horizontal Axis : [2. 6.]


In [ ]:
#Standard devaition of 2 d array
import numpy as np

# create a 2D array
array1 = np.array([[2, 5, 9],
                 [3, 8, 11],
                 [4, 6, 7]])

# compute standard deviation along horizontal axis
result1 = np.std(array1, axis=1)
print("Standard deviation along horizontal axis:", result1)

# compute standard deviation along vertical axis
result2 = np.std(array1, axis=0)
print("Standard deviation  along vertical axis:", result2)

# compute standard deviation of entire array
result3 = np.std(array1)
print("Standard deviation of entire array:", result3)


In [23]:
#NUmpy Broadcasting
#In NumPy, we can perform mathematical operations on arrays of different shapes. An array with a smaller shape is expanded to match the shape of a larger one.
#This is called broadcasting.

# create 1-D array
array1 = np.array([1, 2, 3])

# create 2-D array
array2 = np.array([[1], [2], [3]])

# add arrays of different dimension
# size of array1 expands to match with array2
sum = array1 + array2

print(sum)



[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [24]:
import numpy as np
#median of 1d array
# create a 1D array with 5 elements ood elements
array1 = np.array([1, 2, 3, 4, 5])

# create a 1D array with 6 elements even elements.
#the median is calculated as the average of the two middle elements (3 and 4) i.e. 3.5.
array2 = np.array([1, 2, 3, 4, 5, 7])

# calculate the median
median1 = np.median(array1)
median2 = np.median(array2)

print(median1)
print(median2)

3.0
3.5


In [27]:
import numpy as np

#Median of 2d array
# create a 2D array
array1 = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
#•if	axis = 0, median is calculated along vertical axis
#•if	axis = 1, median is calculated along horizontal axis
#If we don't use the axis parameter, the median is computed over the entire array.

# compute median along horizontal axis
result1 = np.median(array1, axis=1)
print("Median along horizontal axis :", result1)
# compute median along vertical axis
result2 = np.median(array1, axis=0)
print("Median along vertical axis:", result2)
# compute median of entire array
result3 = np.median(array1)
print("Median of entire array:", result3)


Median along horizontal axis : [ 4. 10. 16.]
Median along vertical axis: [ 8. 10. 12.]
Median of entire array: 10.0


In [30]:
#Searching arrays using where.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)
y = np.where(arr%2 == 0)
print(y)
z = np.where(arr%2 == 1)
print(z)

#Sorting arrays
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)
[0 1 2 3]
