<a href="https://colab.research.google.com/github/Sidd-04/PythonLec/blob/master/Numpy_%26Pandas_06_04_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install numpy
#!pip install pandas

import numpy as np
import pandas as pd

l1=[1,2,3,4,5]
t1=(7,8,9,99)
a1=np.array(l1)
print(a1)

In [ ]:
print(type(a1))

In [ ]:
a1[2:3]

In [ ]:
a2=np.array(t1)
print(a2)
print(type(a2))

In [ ]:
#2d array
import numpy as np
l1=[1,2,3,4,5]
l2=[0,0,0,0]
a3=np.array([l1,l2])
print(a3)

In [ ]:
a4=np.arange(0,20,2).reshape(4,5)
print(a4)

In [23]:
a5=np.random.randint(0,100,20).reshape(4,5)  #20 elements
print(a5)

[[11 38 92 80 44]
 [79 52  9 32  1]
 [34 64 25 31 55]
 [92 61 39 73 56]]


In [64]:
a5*=2
print(a5)

[[ 44 152 368 320 176]
 [316 208  36 128   4]
 [136 256 100 124 220]
 [368 244 156 292 224]]


In [65]:
a6=np.arange(0,100).reshape(10,10)
print(a6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [66]:
k=a6[5:6,3:7]
print(k)

[[53 54 55 56]]


In [ ]:
k1=a6[9:10,9:]   #to print 99
print(k1)

reverse=a6[::-1]
print(reverse)

In [53]:
#pandas takes argument as numpy .here df is dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4"],
                                 columns=["col1","col2","col3","col4","col5"])

In [ ]:
print(type(df))
df.head()

In [ ]:
!ls

In [ ]:
%cd /content/drive/Mydrive/

In [ ]:
df1=pd.read_csv('Iris.csv')

In [ ]:
df1.head()
df1.tail()

In [ ]:
#WAP to create a dataset of 12 rows and 14 columns and decorate it with different names and use random fn
import random
ro = ["Name", "Sap id", "course", "college"]
co = ["Name", "Sap id", "course", "college"]
index1 = [random.choice(ro) for i in range(13)]
index2 = [random.choice(co) for j in range(15)]
df = pd.DataFrame(data=np.arange(0,30).reshape(13,14),
                  index=index1,
                  columns=index2)
df.head()

In [ ]:
#TO PLOT DATA THERE ARE TWO LIBRARIES SEABORN AND MATPLOITLIB
#seaborn plot use this library
import seaborn as sns
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),index=["Row1","Row2","Row3","Row4"],
                                 columns=["col1","col2","col3","col4","col5"])
sns.pairplot(df,hue='Species')